### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by franciscop** [arirawr/nofrills-mobile-menu#2]
This link: http://citrondigital.github.io/nofrills-mobile-menu gives a 404

**Comment by arirawr** [comment]
Thanks, fixed!

**Comment by franciscop** [comment]
Sure, still this one missing (that is the one I meant originally):

![nofix](https://cloud.githubusercontent.com/assets/2801252/20087018/65e12810-a5a7-11e6-8014-ff21860a25e8.png)
